#!/bin/csh -f
# ---------------------------------------- 
# PE LAYOUT: 
#   total number of tasks  = 48260 
#   maximum threads per task = 1 
#   cpl ntasks=14400  nthreads=1 rootpe=14400 ninst=1 
#   cam ntasks=28800  nthreads=1 rootpe=0 ninst=1 
#   clm ntasks=1200  nthreads=1 rootpe=0 ninst=1 
#   cice ntasks=9600  nthreads=1 rootpe=1200 ninst=1 
#   pop2 ntasks=19460  nthreads=1 rootpe=28800 ninst=1 
#   sglc ntasks=1  nthreads=1 rootpe=0 ninst=1 
#   swav ntasks=1  nthreads=1 rootpe=0 ninst=1 
#   rtm ntasks=1200  nthreads=1 rootpe=0 ninst=1 
#   
#   total number of hw pes = 48260 
#     cpl hw pe range ~ from 14400 to 28799 
#     cam hw pe range ~ from 0 to 28799 
#     clm hw pe range ~ from 0 to 1199 
#     cice hw pe range ~ from 1200 to 10799 
#     pop2 hw pe range ~ from 28800 to 48259 
#     sglc hw pe range ~ from 0 to 0 
#     swav hw pe range ~ from 0 to 0 
#     rtm hw pe range ~ from 0 to 1199 
# ---------------------------------------- 
cd /home/export/online1/cesm06/dxh/workspace/cesm1_3_beta17_sehires31_newscripts/cases/test76_75plusocn3

./Tools/ccsm_check_lockedfiles || exit -1
source ./Tools/ccsm_getenv     || exit -2

if ($BUILD_COMPLETE != "TRUE") then
  echo "BUILD_COMPLETE is not TRUE"
  echo "Please rebuild the model interactively"
  exit -2
endif

# BATCHQUERY is in env_run.xml
setenv LBQUERY "TRUE"
if !($?BATCHQUERY) then
  setenv LBQUERY "FALSE"
  setenv BATCHQUERY "undefined"
else if ( "$BATCHQUERY" == 'UNSET' ) then
  setenv LBQUERY "FALSE"
  setenv BATCHQUERY "undefined"
endif

# BATCHSUBMIT is in env_run.xml
setenv LBSUBMIT "TRUE"
if !($?BATCHSUBMIT) then
  setenv LBSUBMIT "FALSE"
  setenv BATCHSUBMIT "undefined"
else if ( "$BATCHSUBMIT" == 'UNSET' ) then
  setenv LBSUBMIT "FALSE"
  setenv BATCHSUBMIT "undefined"
endif

# --- Create and cleanup the timing directories---

if !(-d $RUNDIR) mkdir -p $RUNDIR || "cannot make $RUNDIR" && exit -1
if (-d $RUNDIR/timing) rm -r -f $RUNDIR/timing
mkdir $RUNDIR/timing
mkdir $RUNDIR/timing/checkpoints

# --- Determine time-stamp/file-ID string ---
setenv LID "`date +%y%m%d-%H%M%S`"

set sdate = `date +"%Y-%m-%d %H:%M:%S"`
echo "run started $sdate" >>& $CASEROOT/CaseStatus

echo "-------------------------------------------------------------------------"
echo " CESM BUILDNML SCRIPT STARTING"
echo " - To prestage restarts, untar a restart.tar file into $RUNDIR"

cd $CASEROOT
./preview_namelists 
if ($status != 0) then
   echo "ERROR from preview namelist - EXITING"
   exit -1
endif

echo " CESM BUILDNML SCRIPT HAS FINISHED SUCCESSFULLY"
echo "-------------------------------------------------------------------------"
echo "-------------------------------------------------------------------------"
echo " CESM BUILDNML SCRIPT STARTING"
echo " - To prestage restarts, untar a restart.tar file into $RUNDIR"

cd $CASEROOT
./preview_namelists 
if ($status != 0) then
   echo "ERROR from preview namelist - EXITING"
   exit -1
endif

echo " CESM BUILDNML SCRIPT HAS FINISHED SUCCESSFULLY"
echo "-------------------------------------------------------------------------"
